// libs/blog-admin/ui/common/src/lib/UserRoleBadge.svelte
<script lang="ts">
  import type { User } from '@dans-coding-world/prisma-schema';

  interface Props {
    role?: User['role'];
  }

  let { role }: Props = $props();

  const roleConfig: Record<
    User['role'],
    { icon: string; bg: string; text: string; border: string }
  > = {
    ADMIN: {
      icon: 'fa fa-wrench',
      bg: 'bg-[var(--color-error-bg)]',
      text: 'text-[var(--color-error)]',
      border: 'border-[var(--color-error-border)]',
    },
    MOD: {
      icon: 'fa fa-shield',
      bg: 'bg-[var(--color-info-bg)]',
      text: 'text-[var(--color-info)]',
      border: 'border-[var(--color-info-border)]',
    },
    AUTHOR: {
      icon: 'fa fa-pencil',
      bg: 'bg-[var(--color-accent-subtle)]',
      text: 'text-[var(--color-accent)]',
      border: 'border-[var(--color-border-emphasis)]',
    },
    USER: {
      icon: 'fa fa-user',
      bg: 'bg-[var(--color-bg-surface-hover)]',
      text: 'text-[var(--color-text-secondary)]',
      border: 'border-[var(--color-border-subtle)]',
    },
  };

  const config = $derived(
    (role && roleConfig[role]) ?? {
      icon: 'fa fa-user',
      bg: 'bg-[var(--color-bg-muted)]',
      text: 'text-[var(--color-text-tertiary)]',
      border: 'border-[var(--color-border-subtle)]',
    },
  );
</script>

<span
  class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold tracking-wider uppercase border transition-colors {config.bg} {config.text} {config.border}"
>
  <i class="{config.icon} text-[0.7rem]" aria-hidden="true"></i>
  {role}
</span>

// libs/public-blog/ui/common/src/lib/components/UserRoleBadge.tsx
import { User } from '@dans-coding-world/prisma-schema';
import styled from 'styled-components';

const roleConfig: Record<User['role'], { icon: string; color: string }> = {
  ADMIN: { icon: 'fa fa-wrench', color: '#c0392b' },
  MOD: { icon: 'fa fa-shield', color: '#8e44ad' },
  AUTHOR: { icon: 'fa fa-pencil', color: '#2471a3' },
  USER: { icon: 'fa fa-user', color: '#1e8449' },
};

const StyledBadge = styled.span<
  React.ComponentPropsWithoutRef<'span'> & { $color: string }
>`
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 0.4em 0.8em;
  border-radius: 500px;
  font-weight: 600;
  font-size: small;
  text-transform: uppercase;
  background-color: ${({ $color }) => `${$color}18`};
  color: ${({ $color }) => $color};
  border: 1px solid ${({ $color }) => `${$color}40`};
`;

export function UserRoleBadge({ role }: { role: User['role'] }) {
  const config = roleConfig[role] ?? { icon: 'fa fa-user', color: '#888' };
  return (
    <StyledBadge $color={config.color}>
      <i className={config.icon} style={{ fontSize: '0.7rem' }} />
      {role}
    </StyledBadge>
  );
}
