// libs/public-blog/ui/common/src/lib/components/Modal.tsx
import React, { useRef } from 'react';
import styled from 'styled-components';

const StyledDialog = styled.dialog<React.ComponentPropsWithRef<'dialog'>>`
  border: none;
  padding: 0;
  margin: 0;
  inset: 0;
  position: fixed;
  width: 100%;
  height: 100%;
  background: transparent;
  display: grid;
  place-items: center;

  &::backdrop {
    display: none;
  }
`;

const Backdrop = styled.div<React.ComponentPropsWithoutRef<'div'>>`
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
`;

const ModalWrapper = styled.div`
  position: relative;
  z-index: 10;
  display: grid;
  place-content: center;
  background-color: ${({ theme }) => theme.background.surface};
  color: ${({ theme }) => theme.text.primary};
  border-radius: 0.75rem;
`;

const ModalContent = styled.div<React.ComponentPropsWithoutRef<'div'>>`
  position: relative;
  width: 100%;
  padding: 1.5rem;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
`;

const Title = styled.h2`
  font-size: 1.4rem;
  font-weight: 700;
  margin: 0 0 1.5rem;
`;

const CloseButton = styled.button<React.ComponentPropsWithoutRef<'button'>>`
  position: absolute;
  top: 1rem;
  right: 1rem;
  width: 2rem;
  height: 2rem;
  border-radius: 50%;
  border: none;
  background-color: ${({ theme }) => theme.background.elevated};
  font-size: 1rem;
  cursor: pointer;
  transition: 0.2s;

  &:hover {
    color: ${({ theme }) => theme.accent.hover};
  }
`;

type ModalProps = React.DialogHTMLAttributes<HTMLDialogElement> & {
  modalTitle?: string;
  showCloseButton?: boolean;
  onClose?: () => void;
};

export function Modal({
  children,
  title = 'Modal Window',
  showCloseButton = true,
  onClose,
  ...rest
}: ModalProps) {
  const dialogRef = useRef<HTMLDialogElement>(null);

  const closeModal = () => {
    dialogRef.current?.close();
    onClose?.();
  };

  const handleBackdropClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) closeModal();
  };

  return (
    <StyledDialog ref={dialogRef} {...rest}>
      <Backdrop onClick={handleBackdropClick} />

      <ModalWrapper>
        <ModalContent onClick={(e) => e.stopPropagation()}>
          <Title>{title}</Title>

          {showCloseButton && (
            <CloseButton onClick={closeModal} aria-label="Close dialog">
              <i className="fa fa-close"></i>
            </CloseButton>
          )}

          {children}
        </ModalContent>
      </ModalWrapper>
    </StyledDialog>
  );
}

export default Modal;

// libs/blog-admin/ui/common/src/lib/Modal.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLDialogAttributes } from 'svelte/elements';
  import { fade } from 'svelte/transition';

  interface Props extends HTMLDialogAttributes {
    modalTitle?: string;
    showCloseButton?: boolean;
    onClose?: () => void;
    children?: Snippet;
  }

  let {
    modalTitle = 'Modal Window',
    showCloseButton = true,
    onClose,
    children,
    ...restProps
  }: Props = $props();

  let dialogRef = $state<HTMLDialogElement | null>(null);

  function closeModal() {
    dialogRef?.close();
    onClose?.();
  }

  function handleBackdropClick(e: MouseEvent) {
    if (e.target === e.currentTarget) {
      closeModal();
    }
  }
</script>

<dialog
  bind:this={dialogRef}
  {...restProps}
  aria-modal="true"
  class="fixed inset-0 z-99 m-0 grid h-full w-full place-items-center border-none bg-transparent p-0 backdrop:hidden"
>
  <div
    onclick={handleBackdropClick}
    aria-hidden="true"
    transition:fade={{ duration: 150 }}
    class="fixed inset-0 bg-black/50"
  ></div>

  <div
    class="bg-(--color-bg-surface) text-(--color-text-primary) relative z-10 grid place-content-center rounded-xl"
  >
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
    <div
      role="document"
      onclick={(e) => e.stopPropagation()}
      class="relative w-full p-6 shadow-[0_10px_30px_rgba(0,0,0,0.2)]"
    >
      <h2 class="mb-6 text-[1.4rem] font-bold leading-none">{modalTitle}</h2>

      {#if showCloseButton}
        <button
          onclick={closeModal}
          class="bg-(--color-bg-surface-hover) hover:text-(--color-accent) absolute top-4 right-4
           inline-flex h-8 w-8 items-center justify-center rounded-full border-none
            text-base cursor-pointer transition-colors duration-200"
          aria-label="Close dialog"
        >
          <i class="fa fa-close"></i>
        </button>
      {/if}

      {@render children?.()}
    </div>
  </div>
</dialog>
